//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaCloud.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentDiary
    {
        public long ID { get; set; }
        public string Title { get; set; }
        public long CompanyId { get; set; }
        public long BranchId { get; set; }
        public string CustomerId { get; set; }
        public string PackageId { get; set; }
        public System.DateTime DateTimeScheduled { get; set; }
        public int AppointmentLength { get; set; }
        public string Notes { get; set; }
        public int StatusENUM { get; set; }
    }
}
