//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaCloud.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public long BranchID { get; set; }
        public long CompanyID { get; set; }
        public string BranchRegion { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string BranchHotelName { get; set; }
        public string BranchSpaName { get; set; }
        public string BranchAddress { get; set; }
        public string BranchCity { get; set; }
        public string BranchState { get; set; }
        public string BranchCountry { get; set; }
        public string BranchContactNo { get; set; }
        public string BranchComment { get; set; }
        public string BranchIsActive { get; set; }
        public string BranchCreatedBy { get; set; }
        public System.DateTime BranchCreatedDt { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
