//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaCloud.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchTreatmentCost
    {
        public long BranchTreatmentCostID { get; set; }
        public long BranchID { get; set; }
        public long CompanyID { get; set; }
        public long PackageTreatmentXrefID { get; set; }
        public decimal TreatmentCost { get; set; }
        public string Comments { get; set; }
    }
}
