//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaCloud.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public long EmpID { get; set; }
        public long CompanyID { get; set; }
        public long BaseBranchID { get; set; }
        public string EmpCode { get; set; }
        public string EmpFName { get; set; }
        public string EmpLName { get; set; }
        public string EmpGender { get; set; }
        public Nullable<int> EmpTypeID { get; set; }
        public string IsOnPayRoll { get; set; }
        public string EmpContactNo { get; set; }
        public string IsActive { get; set; }
        public System.DateTime EmpCreatedDt { get; set; }
        public string EmpCreatedBy { get; set; }
    
        public virtual EmployeeType EmployeeType { get; set; }
    }
}
