//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaCloud.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryRqdForTreatment
    {
        public long InventoryRqdForTreatmentID { get; set; }
        public long TreatmentID { get; set; }
        public long ProductID { get; set; }
        public Nullable<decimal> QtyUsed { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Treatment Treatment { get; set; }
    }
}
