//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaCloud.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membership
    {
        public long MembershipID { get; set; }
        public long CompanyID { get; set; }
        public string MembershipName { get; set; }
        public string MembershipDesc { get; set; }
        public Nullable<decimal> MembershipCost { get; set; }
        public Nullable<int> MembershipDurationMonths { get; set; }
    }
}
