//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaCloud.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.InventoryRqdForServices = new HashSet<InventoryRqdForService>();
            this.XrefServiceTreatments = new HashSet<XrefServiceTreatment>();
        }
    
        public long ServiceID { get; set; }
        public long CompanyID { get; set; }
        public string ServiceName { get; set; }
        public string ServiceDesc { get; set; }
        public System.DateTime CreatedDt { get; set; }
    
        public virtual ICollection<InventoryRqdForService> InventoryRqdForServices { get; set; }
        public virtual ICollection<XrefServiceTreatment> XrefServiceTreatments { get; set; }
    }
}
