//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaCloud.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        public Treatment()
        {
            this.XrefPackageTreatments = new HashSet<XrefPackageTreatment>();
        }
    
        public long TreatmentID { get; set; }
        public long CompanyID { get; set; }
        public string TreatmentName { get; set; }
        public string TreatmentDesc { get; set; }
        public System.DateTime CreatedDt { get; set; }
    
        public virtual ICollection<XrefPackageTreatment> XrefPackageTreatments { get; set; }
    }
}
