//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaCloud.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public long VoucherID { get; set; }
        public long CompanyID { get; set; }
        public string VoucherCode { get; set; }
        public string VoucherDesc { get; set; }
        public Nullable<System.DateTime> VoucherStartDt { get; set; }
        public Nullable<System.DateTime> VoucherEndDt { get; set; }
        public string IsVoucherActive { get; set; }
        public Nullable<decimal> VoucherAmount { get; set; }
    }
}
