//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaCloud.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XrefPackageTreatment
    {
        public long PackageTreatmentXrefID { get; set; }
        public long PackageID { get; set; }
        public long TreatmentID { get; set; }
        public long CompanyID { get; set; }
    
        public virtual Package Package { get; set; }
        public virtual Treatment Treatment { get; set; }
    }
}
